### ISSUE TITLE
icons do not scale well with the smaller version on button

### ISSUE THREAD

**Issue by Lubbe91** [youseedk/dna#243] opened 2020-03-03 11:10 UTC
The icon is a little big with the new smaller version of the button

Original:
![image](https://user-images.githubusercontent.com/2743537/75770083-93aef780-5d47-11ea-981f-15f55d6bb081.png)

Small:
![image](https://user-images.githubusercontent.com/2743537/75770100-9d385f80-5d47-11ea-9459-09df0658cdf8.png)

And if no text is provided, the icon disappears.

No text original:
![image](https://user-images.githubusercontent.com/2743537/75770390-1cc62e80-5d48-11ea-8db1-803f05319606.png)

No text small:
![image](https://user-images.githubusercontent.com/2743537/75770343-0ae48b80-5d48-11ea-90f0-44b1b312ed5a.png)

**Comment by havgry** [comment] 2020-05-04 13:00
This *is* a bug but it's not clear to me what the expected outcome is. The `small` modifier only reduces the font-size and horizontal padding - the icon disappears due to the latter. As such, it doesn't really make much sense to apply the `small` modifier to icon-only buttons.

**Comment by Lubbe91** [comment] 2020-05-04 21:35
My thought was that, when `small` is applied, it would offer a smaller version of both text and icons, to accommodate smaller screens. 

But I've test it on my phone and it actually looks alright when it's icon-only.
![Image from iOS](https://user-images.githubusercontent.com/2743537/81015831-a638d080-8e5f-11ea-995d-b7d0805c052b.png)

But I would still argue that text & icon combination, needs to match a bit better in size.

**Comment by grandorf** [comment] 2020-11-12 09:37
@Lubbe91 can you look at this? The issue is 6 months old. So I would argue that we need to fix the issue or decide not to prioritise it and close it.

**Comment by Lubbe91** [comment] 2020-11-16 06:26
I think we can close this one @grandorf

**Closed** 2020-11-18 16:41 UTC
Labels: bug
